### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mansya** [at-internet/atinternet-android-sdk#11]
Hi, @at-internet I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by BenDz** [comment]
Hi @mansya 
Thank you for your contribution, but we - as a company - already have a logo for our brand.
We'll check to add it to this project.
Best,
Benjamin
