### ISSUE TITLE
'A connection was leaked' warning

### ISSUE THREAD

**Issue by jelleheemskerk** [at-internet/atinternet-android-sdk#22]
We're getting warnings about connection leaks in `OkHttpClient` when using this SDK.

> 2020-01-06 14:25:42.309 8131-8616/com.atinternet W/OkHttpClient: A connection to https://logs.xiti.com/ was leaked. Did you forget to close a response body?

- Warning occurs in the [TestApp](https://github.com/at-internet/atinternet-android-sdk/tree/2.14.0/ATMobileAnalytics/TestApp) and our own apps
- Warning seems to occur on certain devices (not all)

#### Tested with
- Version **2.12.0** and **2.14.0**
- **Huawei P20 Lite (ANE-LX1, Android 8.0)**

**Comment by nsagnett** [comment]
I cannot reproduce it.

However, in the documentation, calling the disconnect should be sufficient to release ressources : https://developer.android.com/reference/java/net/HttpURLConnection, and we don't read the body

**Comment by jelleheemskerk** [comment]
It seems to be the device. Thanks for checking!
