### ISSUE TITLE
Proguard rules should be provided by library

### ISSUE THREAD

**Issue by hameno** [at-internet/atinternet-android-sdk#27]
Android libraries can and should ship their own proguard rules instead of relying on an external documentation. Please include the default rules into the SDK.

**Comment by nsagnett** [comment]
Thanks for the feedback.

I created a branch (https://github.com/at-internet/atinternet-android-sdk/tree/proguard), can you try it let me know if it's ok for you.

Regards

**Comment by hameno** [comment]
Can't test right now, but the changes look good.

**Comment by nsagnett** [comment]
OK thanks, it will be available in the next release in few time.

**Comment by nsagnett** [comment]
Hi ! 

It's ok since 2.17.0, released today 

Regards
