### ISSUE TITLE
Add a method to hide the debugger view

### ISSUE THREAD

**Issue by rpradal** [at-internet/atinternet-android-sdk#3]
Hi,

This more a (small) feature request than an issue :
Could you add a method to your Debugger class singleton to hide the debugger view ?

Thank you !

**Comment by nsagnett** [comment]
Hello !

If the Debugger view is visible, you have called Debugger.show method in your code.
Remove it and the view will be disabled.

**Comment by rpradal** [comment]
Thank you for your quick reply :)

I want to be able to dynamically (at runtime) show or hide the debugger view : the solution you propose will not fulfill this goal.

**Comment by BenDz** [comment]
Hi Rémi,
Thanks for the suggestion. We take it into account for a future release.

**Comment by BenDz** [comment]
Hi Rémi,
We just pushed online the v2.1.1, which include this feature.
Please refer to our online documentation for more information: http://developers.atinternet-solutions.com/android-en/getting-started-android-en/debugger-android-en/#utilisation_2
