### ISSUE TITLE
Crash when initializing sdk using android 11 with mobile data on

### ISSUE THREAD

**Issue by iliaskomp** [at-internet/atinternet-android-sdk#30]
We have integrated this sdk in our app. We recently updated targetSdk to 30 and we experience crashes for android 11 devices:
This is reproducible on android 11 emulator:
- Only mobile data on (wifi off)
- Initialize xiti
- App crashes

**Stacktrace**
```
     Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.atinternet.tracker.TechnicalContext.getConnection(Core.java:1124)
        at com.atinternet.tracker.Sender.isNetworkOnline(Core.java:789)
        at com.atinternet.tracker.Sender.sendOfflineHits(Core.java:758)
        at com.atinternet.tracker.Offline.dispatch(Offline.java:107)
        .....
```

It seems that `TelephonyManager.getNetworkType` is deprecated and the suggestion is to use `getDataNetworkType()` instead.

**Comment by nsagnett** [comment]
It seems to be a permission issue, you probably have forgotten to add permission into your manifest : https://developer.android.com/reference/android/telephony/TelephonyManager#getDataNetworkType()

**Comment by iliaskomp** [comment]
Hi Nicolas, thanks for the response.
That is true but we would like to avoid adding this runtime permission since it is certain to lead to a lot of user complaints.
I am not aware of the specifics of the sdk but it seems that getting the network type in the sdk isn't necessary for sending an event. A solution could be, for example, that the exception is caught and an UNKNOWN network type is returned

**Comment by iliaskomp** [comment]
Is there any decision on this yet?
It would be great if a workaround could be implemented on the sdk side.

**Comment by nsagnett** [comment]
Hi, 

We just released 2.20.2 version which fix your problem

Regards,

**Comment by iliaskomp** [comment]
Thank you, I just tested it and there is no crash now :+1:

**Comment by mehdi5599** [comment]
> We have integrated this sdk in our app. We recently updated targetSdk to 30 and we experience crashes for android 11 devices:
> This is reproducible on android 11 emulator:
> - Only mobile data on (wifi off)
> - Initialize xiti
> - App crashes
> 
> **Stacktrace**
> ```
>      Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
>         at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
>         at android.os.Parcel.createException(Parcel.java:2357)
>         at android.os.Parcel.readException(Parcel.java:2340)
>         at android.os.Parcel.readException(Parcel.java:2282)
> at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
>         at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
>         at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
>         at com.atinternet.tracker.TechnicalContext.getConnection(Core.java:1124)
>         at com.atinternet.tracker.Sender.isNetworkOnline(Core.java:789)
>         at com.atinternet.tracker.Sender.sendOfflineHits(Core.java:758)
>         at com.atinternet.tracker.Offline.dispatch(Offline.java:107)
>         .....
> ```
> 
> It seems that `TelephonyManager.getNetworkType` is deprecated and the suggestion is to use `getDataNetworkType()` instead.
