### ISSUE TITLE
Migrate from jcenter before May 1st 2021

### ISSUE THREAD

**Issue by vuongp** [at-internet/atinternet-android-sdk#31]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

https://developers.atinternet-solutions.com/android-en/getting-started-android-en/integration-of-the-library-android-en/#using-jcenter-dependency_3

Will this sdk be available on maven central for example?

**Comment by nsagnett** [comment]
We are working on it yes to migrate to maven central

**Comment by nsagnett** [comment]
We released all versions since 2.14.0 in MavenCentral
