### ISSUE TITLE
Debugger icon invisible

### ISSUE THREAD

**Issue by Trowa** [at-internet/atinternet-android-sdk#4]
Hi,

I'm using a navigation drawer library (https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer) and the icon of your debugger is not visible with their layout. Any idea about the reason ? By the way, it could be really helpfull if we could have a function to perform a click on the icon or display the debugger programatically.

**Comment by nsagnett** [comment]
Hi !

If you are using the sdk latest version, icon is attached to the window, so it should work.

**Comment by Trowa** [comment]
Hi,

After further investigation, I moved the creation of the debugger on fragment and now it's works, but not on the first one, I have to go on a second fragment to make the icon appears.

**Comment by nsagnett** [comment]
Try to put Debugger creation on your first Activity onCreate
