### ISSUE TITLE
Question: ATTag.getINSTANCE().getUniqueId(); alternative in the new SDK

### ISSUE THREAD

**Issue by bradroid** [at-internet/atinternet-android-sdk#5]
Hello, I've recently updated to newest SDK version from the really old one, and I'm struggling to update the following code to make it compatible with the new SDK version:

`ATTag.getINSTANCE().getUniqueId();`

Is there a method in the new SDK which does the same thing? Please help.

**Comment by nsagnett** [comment]
Hello ! 

Two methods are available now : 
- Since 2.0.0, async method is implemented: 
```
tracker.getUserId(new UserIdCallback() {
            @Override
            public void receiveUserId(String id) {
                Log.d(null, "Current idclient is : " + id);
            }
        });
```
- Since 2.3.0, sync method is available BUT YOU HAVE TO send a first hit before using it : 
`tracker.getUserIdSync();`

Best Regards
